export default {
  name: 'treatmentPackage',
  title: 'Pakiety zabiegowe',
  type: 'document',
  fields: [
    {
      name: 'name',
      title: 'Nazwa pakietu',
      type: 'string',
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: 'slug',
      title: 'Slug pakietu',
      type: 'slug',
      options: {
        source: 'name',
        maxLength: 96,
      },
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: 'description',
      title: 'Opis pakietu',
      type: 'text',
      rows: 3,
      description: 'Krótki opis widoczny przy pakiecie.',
    },
    {
      name: 'price',
      title: 'Cena bazowa',
      type: 'number',
      description: 'Kwota przechowywana jako liczba, używana w przyszłej integracji z bramką płatności.',
      validation: (Rule: any) => Rule.required().min(0),
    },
    {
      name: 'currency',
      title: 'Waluta',
      type: 'string',
      initialValue: 'PLN',
      options: {
        list: [
          { title: 'PLN', value: 'PLN' },
          { title: 'EUR', value: 'EUR' },
          { title: 'USD', value: 'USD' },
        ],
        layout: 'dropdown',
      },
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: 'priceText',
      title: 'Etykieta ceny',
      type: 'string',
      description: 'Opcjonalna etykieta ceny do wyświetlania, np. "od 2700 zł" lub "2700 zł".',
    },
    {
      name: 'features',
      title: 'Lista korzyści i elementów pakietu',
      type: 'array',
      of: [{ type: 'string' }],
      description: 'Wymień elementy pakietu, które mają być wyświetlane jako lista.',
    },
    {
      name: 'tags',
      title: 'Tagi usług',
      type: 'array',
      of: [{ type: 'string' }],
      options: {
        layout: 'tags',
        list: [
          { title: 'chirurgia', value: 'chirurgia' },
          { title: 'ortopedia', value: 'ortopedia' },
          { title: 'podologia', value: 'podologia' },
          { title: 'podochirurgia', value: 'podochirurgia' },
          { title: 'laseroterapia', value: 'laseroterapia' },
          { title: 'medycyna-estetyczna', value: 'medycyna-estetyczna' },
          { title: 'wazektomia', value: 'wazektomia' },
          { title: 'leczenie-ran', value: 'leczenie-ran' },
        ],
      },
      description: 'Tagi używane do powiązania pakietu z konkretną podstroną usług.',
    },
    {
      name: 'isPromoted',
      title: 'Rekomendowany pakiet',
      type: 'boolean',
      initialValue: false,
    },
    {
      name: 'order',
      title: 'Kolejność wyświetlania',
      type: 'number',
      description: 'Mniejsza liczba pokazuje pakiet wyżej na liście.',
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: 'active',
      title: 'Widoczny w ofercie',
      type: 'boolean',
      initialValue: true,
      description: 'Wyłączony pakiet nie będzie wyświetlany klientom.',
    },
    {
      name: 'paymentProductId',
      title: 'ID produktu płatności',
      type: 'string',
      description: 'Opcjonalny identyfikator produktu w bramce płatności (np. Stripe, PayU).',
    },
    {
      name: 'paymentPriceId',
      title: 'ID ceny płatności',
      type: 'string',
      description: 'Opcjonalny identyfikator ceny w bramce płatności.',
    },
  ],
  orderings: [
    {
      title: 'Według kolejności wyświetlania',
      name: 'orderAsc',
      by: [{ field: 'order', direction: 'asc' }],
    },
  ],
};
